config/routes.rb
Rails.application.routes.draw do
  resources :proposta

  resources :agendamento_de_visitas

  resources :imovels

  resources :usuarios

  resources :proprietarios

  resources :tipo_de_imovels

  root 'proprietarios#index'

end

app/models/tipo_de_imovel.rb
class TipoDeImovel < ActiveRecord::Base
end

app/controllers/tipo_de_imovels_controller.rb
class TipoDeImovelsController < ApplicationController
  before_action :set_tipo_de_imovel, only: [:show, :edit, :update, :destroy]

  # GET /tipo_de_imovels
  # GET /tipo_de_imovels.json
  def index
    @tipo_de_imovels = TipoDeImovel.all
  end

  # GET /tipo_de_imovels/1
  # GET /tipo_de_imovels/1.json
  def show
  end

  # GET /tipo_de_imovels/new
  def new
    @tipo_de_imovel = TipoDeImovel.new
  end

  # GET /tipo_de_imovels/1/edit
  def edit
  end

  # POST /tipo_de_imovels
  # POST /tipo_de_imovels.json
  def create
    @tipo_de_imovel = TipoDeImovel.new(tipo_de_imovel_params)

    respond_to do |format|
      if @tipo_de_imovel.save
        format.html { redirect_to @tipo_de_imovel, notice: 'Tipo de imovel was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_de_imovel }
      else
        format.html { render :new }
        format.json { render json: @tipo_de_imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_de_imovels/1
  # PATCH/PUT /tipo_de_imovels/1.json
  def update
    respond_to do |format|
      if @tipo_de_imovel.update(tipo_de_imovel_params)
        format.html { redirect_to @tipo_de_imovel, notice: 'Tipo de imovel was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_de_imovel }
      else
        format.html { render :edit }
        format.json { render json: @tipo_de_imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_de_imovels/1
  # DELETE /tipo_de_imovels/1.json
  def destroy
    @tipo_de_imovel.destroy
    respond_to do |format|
      format.html { redirect_to tipo_de_imovels_url, notice: 'Tipo de imovel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_de_imovel
      @tipo_de_imovel = TipoDeImovel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_de_imovel_params
      params.require(:tipo_de_imovel).permit(:descricao, :tipoDeContrato, :valor)
    end
end

app/helpers/tipo_de_imovels_helper.rb
module TipoDeImovelsHelper
end

app/views/tipo_de_imovels/_form.html.haml
= form_for @tipo_de_imovel do |f|
  - if @tipo_de_imovel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tipo_de_imovel.errors.count, "error")} prohibited this tipo_de_imovel from being saved:"
      %ul
        - @tipo_de_imovel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :descricao
    = f.text_field :descricao
  .field
    = f.label :tipoDeContrato
    = f.text_field :tipoDeContrato
  .field
    = f.label :valor
    = f.text_field :valor
  .actions
    = f.submit 'Save'

app/views/tipo_de_imovels/edit.html.haml
%h1 Editing Tipo de Imovel

= render 'form'

= link_to 'Show', @tipo_de_imovel
\|
= link_to 'Back', tipo_de_imovels_path

app/views/tipo_de_imovels/index.html.haml
%h1 Tipo de Imoveis

%table
  %tr
    %th Descricao
    %th Tipodecontrato
    %th Valor
    %th
    %th
    %th

  - @tipo_de_imovels.each do |tipo_de_imovel|
    %tr
      %td= tipo_de_imovel.descricao
      %td= tipo_de_imovel.tipoDeContrato
      %td= tipo_de_imovel.valor
      %td= link_to 'Show', tipo_de_imovel
      %td= link_to 'Edit', edit_tipo_de_imovel_path(tipo_de_imovel)
      %td= link_to 'Destroy', tipo_de_imovel, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tipo de imovel', new_tipo_de_imovel_path

app/views/tipo_de_imovels/new.html.haml
%h1 New Tipo de Imovel

= render 'form'

= link_to 'Back', tipo_de_imovels_path

app/views/tipo_de_imovels/show.html.haml
%p#notice= notice

%p
  %b Descricao:
  = @tipo_de_imovel.descricao
%p
  %b Tipodecontrato:
  = @tipo_de_imovel.tipoDeContrato
%p
  %b Valor:
  = @tipo_de_imovel.valor

= link_to 'Edit', edit_tipo_de_imovel_path(@tipo_de_imovel)
\|
= link_to 'Back', tipo_de_imovels_path