config/routes.rb
Rails.application.routes.draw do
  resources :proposta

  resources :agendamento_de_visitas

  resources :imovels

  resources :usuarios

  resources :proprietarios

  resources :tipo_de_imovels

  root 'proprietarios#index'

end

app/models/proprietario.rb
class Proprietario < ActiveRecord::Base
end

app/controllers/proprietarios_controller.rb
class ProprietariosController < ApplicationController
  before_action :set_proprietario, only: [:show, :edit, :update, :destroy]

  # GET /proprietarios
  # GET /proprietarios.json
  def index
    @proprietarios = Proprietario.all
  end

  # GET /proprietarios/1
  # GET /proprietarios/1.json
  def show
  end

  # GET /proprietarios/new
  def new
    @proprietario = Proprietario.new
  end

  # GET /proprietarios/1/edit
  def edit
  end

  # POST /proprietarios
  # POST /proprietarios.json
  def create
    @proprietario = Proprietario.new(proprietario_params)

    respond_to do |format|
      if @proprietario.save
        format.html { redirect_to @proprietario, notice: 'Proprietario was successfully created.' }
        format.json { render :show, status: :created, location: @proprietario }
      else
        format.html { render :new }
        format.json { render json: @proprietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proprietarios/1
  # PATCH/PUT /proprietarios/1.json
  def update
    respond_to do |format|
      if @proprietario.update(proprietario_params)
        format.html { redirect_to @proprietario, notice: 'Proprietario was successfully updated.' }
        format.json { render :show, status: :ok, location: @proprietario }
      else
        format.html { render :edit }
        format.json { render json: @proprietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proprietarios/1
  # DELETE /proprietarios/1.json
  def destroy
    @proprietario.destroy
    respond_to do |format|
      format.html { redirect_to proprietarios_url, notice: 'Proprietario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proprietario
      @proprietario = Proprietario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proprietario_params
      params.require(:proprietario).permit(:nome, :endereco, :cpf, :telefone, :email)
    end
end

app/helpers/proprietarios_helper.rb
module ProprietariosHelper
end

app/views/proprietarios/_form.html.haml
= form_for @proprietario do |f|
  - if @proprietario.errors.any?
    #error_explanation
      %h2= "#{pluralize(@proprietario.errors.count, "error")} prohibited this proprietario from being saved:"
      %ul
        - @proprietario.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :endereco
    = f.text_field :endereco
  .field
    = f.label :cpf
    = f.text_field :cpf
  .field
    = f.label :telefone
    = f.text_field :telefone
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/proprietarios/edit.html.haml
%h1 Editing Proprietario

= render 'form'

= link_to 'Show', @proprietario
\|
= link_to 'Back', proprietarios_path

app/views/proprietarios/index.html.haml
%h1 Proprietarios

%table
  %tr
    %th Nome
    %th Endereco
    %th Cpf
    %th Telefone
    %th Email
    %th
    %th
    %th

  - @proprietarios.each do |proprietario|
    %tr
      %td= proprietario.nome
      %td= proprietario.endereco
      %td= proprietario.cpf
      %td= proprietario.telefone
      %td= proprietario.email
      %td= link_to 'Show', proprietario
      %td= link_to 'Edit', edit_proprietario_path(proprietario)
      %td= link_to 'Destroy', proprietario, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Proprietario', new_proprietario_path

app/views/proprietarios/new.html.haml
%h1 New Proprietario

= render 'form'

= link_to 'Back', proprietarios_path

app/views/proprietarios/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @proprietario.nome
%p
  %b Endereco:
  = @proprietario.endereco
%p
  %b Cpf:
  = @proprietario.cpf
%p
  %b Telefone:
  = @proprietario.telefone
%p
  %b Email:
  = @proprietario.email

= link_to 'Edit', edit_proprietario_path(@proprietario)
\|
= link_to 'Back', proprietarios_path