config/routes.rb
Rails.application.routes.draw do
  resources :proposta

  resources :agendamento_de_visitas

  resources :imovels

  resources :usuarios

  resources :proprietarios

  resources :tipo_de_imovels

  root 'proprietarios#index'

end

app/models/agendamento_de_visita.rb
class AgendamentoDeVisita < ActiveRecord::Base
  belongs_to :imovel
  belongs_to :usuario
end

app/controllers/agendamento_de_visitas_controller.rb
class AgendamentoDeVisitasController < ApplicationController
  before_action :set_agendamento_de_visita, only: [:show, :edit, :update, :destroy]

  # GET /agendamento_de_visitas
  # GET /agendamento_de_visitas.json
  def index
    @agendamento_de_visitas = AgendamentoDeVisita.all
  end

  # GET /agendamento_de_visitas/1
  # GET /agendamento_de_visitas/1.json
  def show
  end

  # GET /agendamento_de_visitas/new
  def new
    @agendamento_de_visita = AgendamentoDeVisita.new
    @usuarios = Usuario.all
    @imoveis = Imovel.all
  end

  # GET /agendamento_de_visitas/1/edit
  def edit
    @usuarios = Usuario.all
    @imoveis = Imovel.all
  end

  # POST /agendamento_de_visitas
  # POST /agendamento_de_visitas.json
  def create
    @agendamento_de_visita = AgendamentoDeVisita.new(agendamento_de_visita_params)

    respond_to do |format|
      if @agendamento_de_visita.save
        format.html { redirect_to @agendamento_de_visita, notice: 'Agendamento de visita was successfully created.' }
        format.json { render :show, status: :created, location: @agendamento_de_visita }
      else
        format.html { render :new }
        format.json { render json: @agendamento_de_visita.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendamento_de_visitas/1
  # PATCH/PUT /agendamento_de_visitas/1.json
  def update
    respond_to do |format|
      if @agendamento_de_visita.update(agendamento_de_visita_params)
        format.html { redirect_to @agendamento_de_visita, notice: 'Agendamento de visita was successfully updated.' }
        format.json { render :show, status: :ok, location: @agendamento_de_visita }
      else
        format.html { render :edit }
        format.json { render json: @agendamento_de_visita.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendamento_de_visitas/1
  # DELETE /agendamento_de_visitas/1.json
  def destroy
    @agendamento_de_visita.destroy
    respond_to do |format|
      format.html { redirect_to agendamento_de_visitas_url, notice: 'Agendamento de visita was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agendamento_de_visita
      @agendamento_de_visita = AgendamentoDeVisita.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agendamento_de_visita_params
      params.require(:agendamento_de_visita).permit(:data, :hora, :imovel_id, :usuario_id)
    end
end

app/helpers/agendamento_de_visitas_helper.rb
module AgendamentoDeVisitasHelper
end

app/views/agendamento_de_visitas/_form.html.haml
= form_for @agendamento_de_visita do |f|
  - if @agendamento_de_visita.errors.any?
    #error_explanation
      %h2= "#{pluralize(@agendamento_de_visita.errors.count, "error")} prohibited this agendamento_de_visita from being saved:"
      %ul
        - @agendamento_de_visita.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :data
    = f.date_select :data
  .field
    = f.label :hora
    = f.text_field :hora
  .field
    = f.label :imovel_id
    = f.collection_select :imovel_id, @imoveis, :id, :endereco
  .field
    = f.label :usuario_id
    = f.collection_select :usuario_id, @usuarios, :id, :nome
  .actions
    = f.submit 'Save'

app/views/agendamento_de_visitas/edit.html.haml
%h1 Editing Agendamento de Visita

= render 'form'

= link_to 'Show', @agendamento_de_visita
\|
= link_to 'Back', agendamento_de_visitas_path

app/views/agendamento_de_visitas/index.html.haml
%h1 Agendamento de Visitas

%table
  %tr
    %th Data
    %th Hora
    %th Imovel
    %th Usuario
    %th
    %th
    %th

  - @agendamento_de_visitas.each do |agendamento_de_visita|
    %tr
      %td= agendamento_de_visita.data
      %td= agendamento_de_visita.hora
      %td= agendamento_de_visita.imovel
      %td= agendamento_de_visita.usuario
      %td= link_to 'Show', agendamento_de_visita
      %td= link_to 'Edit', edit_agendamento_de_visita_path(agendamento_de_visita)
      %td= link_to 'Destroy', agendamento_de_visita, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Agendamento de visita', new_agendamento_de_visita_path

app/views/agendamento_de_visitas/new.html.haml
%h1 New Agendamento de Visita

= render 'form'

= link_to 'Back', agendamento_de_visitas_path

app/views/agendamento_de_visitas/show.html.haml
%p#notice= notice

%p
  %b Data:
  = @agendamento_de_visita.data
%p
  %b Hora:
  = @agendamento_de_visita.hora
%p
  %b Imovel:
  = @agendamento_de_visita.imovel.endereco
%p
  %b Usuario:
  = @agendamento_de_visita.usuario.nome

= link_to 'Edit', edit_agendamento_de_visita_path(@agendamento_de_visita)
\|
= link_to 'Back', agendamento_de_visitas_path