config/routes.rb
Rails.application.routes.draw do
  resources :proposta

  resources :agendamento_de_visitas

  resources :imovels

  resources :usuarios

  resources :proprietarios

  resources :tipo_de_imovels

  root 'proprietarios#index'

end

app/models/imovel.rb
class Imovel < ActiveRecord::Base
  belongs_to :tipo_de_imovel
  belongs_to :proprietario
end

app/controllers/imovels_controller.rb
class ImovelsController < ApplicationController
  before_action :set_imovel, only: [:show, :edit, :update, :destroy]

  # GET /imovels
  # GET /imovels.json
  def index
    @imovels = Imovel.all
  end

  # GET /imovels/1
  # GET /imovels/1.json
  def show
  end

  # GET /imovels/new
  def new
    @imovel = Imovel.new
      @todosproprietarios = Proprietario.all
      @todosimoveis = TipoDeImovel.all
  end

  # GET /imovels/1/edit
  def edit
    @todosproprietarios = Proprietario.all
    @todosimoveis = TipoDeImovel.all
  end

  # POST /imovels
  # POST /imovels.json
  def create
    @imovel = Imovel.new(imovel_params)

    respond_to do |format|
      if @imovel.save
        format.html { redirect_to @imovel, notice: 'Imovel was successfully created.' }
        format.json { render :show, status: :created, location: @imovel }
      else
        format.html { render :new }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imovels/1
  # PATCH/PUT /imovels/1.json
  def update
    respond_to do |format|
      if @imovel.update(imovel_params)
        format.html { redirect_to @imovel, notice: 'Imovel was successfully updated.' }
        format.json { render :show, status: :ok, location: @imovel }
      else
        format.html { render :edit }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imovels/1
  # DELETE /imovels/1.json
  def destroy
    @imovel.destroy
    respond_to do |format|
      format.html { redirect_to imovels_url, notice: 'Imovel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imovel
      @imovel = Imovel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imovel_params
      params.require(:imovel).permit(:endereco, :area, :quarto, :sala, :cozinha, :banheiro, :areaExterna, :areaDeServico, :garagem, :tipo_de_imovel_id, :proprietario_id)
    end
end

app/helpers/imovels_helper.rb
module ImovelsHelper
end

app/views/imovels/_form.html.haml
= form_for @imovel do |f|
  - if @imovel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@imovel.errors.count, "error")} prohibited this imovel from being saved:"
      %ul
        - @imovel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :endereco
    = f.text_field :endereco
  .field
    = f.label :area
    = f.text_field :area
  .field
    = f.label :quarto
    = f.number_field :quarto
  .field
    = f.label :sala
    = f.number_field :sala
  .field
    = f.label :cozinha
    = f.number_field :cozinha
  .field
    = f.label :banheiro
    = f.number_field :banheiro
  .field
    = f.label :areaExterna
    = f.text_field :areaExterna
  .field
    = f.label :areaDeServico
    = f.text_field :areaDeServico
  .field
    = f.label :garagem
    = f.number_field :garagem
  .field
    = f.label :tipo_de_imovel_id
    = f.collection_select :tipo_de_imovel_id, @todosimoveis, :id, :descricao
  .field
    = f.label :proprietario_id
    = f.collection_select :proprietario_id, @todosproprietarios, :id, :nome
  .actions
    = f.submit 'Save'

app/views/imovels/edit.html.haml
%h1 Editing Imovel

= render 'form'

= link_to 'Show', @imovel
\|
= link_to 'Back', imovels_path

app/views/imovels/index.html.haml
%h1 Imoveis

%table
  %tr
    %th Endereco
    %th Area
    %th Quarto
    %th Sala
    %th Cozinha
    %th Banheiro
    %th Areaexterna
    %th Areadeservico
    %th Garagem
    %th Tipo de imovel
    %th Proprietario
    %th
    %th
    %th

  - @imovels.each do |imovel|
    %tr
      %td= imovel.endereco
      %td= imovel.area
      %td= imovel.quarto
      %td= imovel.sala
      %td= imovel.cozinha
      %td= imovel.banheiro
      %td= imovel.areaExterna
      %td= imovel.areaDeServico
      %td= imovel.garagem
      %td= imovel.tipo_de_imovel
      %td= imovel.proprietario
      %td= link_to 'Show', imovel
      %td= link_to 'Edit', edit_imovel_path(imovel)
      %td= link_to 'Destroy', imovel, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Imovel', new_imovel_path

app/views/imovels/new.html.haml
%h1 New imovel

= render 'form'

= link_to 'Back', imovels_path

app/views/imovels/show.html.haml
%p#notice= notice

%p
  %b Endereco:
  = @imovel.endereco
%p
  %b Area:
  = @imovel.area
%p
  %b Quarto:
  = @imovel.quarto
%p
  %b Sala:
  = @imovel.sala
%p
  %b Cozinha:
  = @imovel.cozinha
%p
  %b Banheiro:
  = @imovel.banheiro
%p
  %b Areaexterna:
  = @imovel.areaExterna
%p
  %b Areadeservico:
  = @imovel.areaDeServico
%p
  %b Garagem:
  = @imovel.garagem
%p
  %b Tipo de imovel:
  = @imovel.tipo_de_imovel.descricao
%p
  %b Proprietario:
  = @imovel.proprietario.nome

= link_to 'Edit', edit_imovel_path(@imovel)
\|
= link_to 'Back', imovels_path